export const SHIPS = {
  frost: {
    id: "frost",
    name: "冰蓝疾锋机",
    englishName: "Frost Spear",
    subtitle: "追踪光梭",
    role: "新手友好 / 高机动",
    description: "光梭命中叠冰标记，空格锁定或引爆目标，适合连锁清场。",
    attack: "标记、锁定、跳弹连杀",
    color: "#69f1ff",
    accent: "#bff8ff",
    speed: 366,
    size: 104,
    drawWidth: 112,
    drawHeight: 108,
    sprite: "playerFrostSpear",
    preview: "./assets/player_frost_spear_sprite.png",
    skillName: "冰晶锁定 / 引爆",
    coreCooldown: 11.5,
    fireDelay: 0.1,
  },
  crimson: {
    id: "crimson",
    name: "赤红重炮机",
    englishName: "Crimson Cannon",
    subtitle: "正面歼灭炮",
    role: "Boss 杀手 / 重火力",
    description: "自动炮只负责补刀，按住空格蓄力，松开打出高爆重炮。",
    attack: "蓄力重炮、热量管理",
    color: "#ff4b55",
    accent: "#ffb02e",
    speed: 318,
    size: 108,
    drawWidth: 118,
    drawHeight: 104,
    sprite: "playerCrimsonCannon",
    preview: "./assets/player_crimson_cannon_sprite.png",
    skillName: "蓄力歼灭炮",
    coreCooldown: 15.5,
    fireDelay: 0.15,
  },
  solar: {
    id: "solar",
    name: "圣金羽翼机",
    englishName: "Solar Wing",
    subtitle: "羽刃光雨",
    role: "广域清场 / 高容错",
    description: "常驻环绕羽刃，空格在防守、展开、回收三种模式间切换。",
    attack: "羽刃模式、清弹控场",
    color: "#ffd86a",
    accent: "#fff3a8",
    speed: 338,
    size: 106,
    drawWidth: 122,
    drawHeight: 106,
    sprite: "playerSolarWing",
    preview: "./assets/player_solar_wing_sprite.png",
    skillName: "羽刃模式切换",
    coreCooldown: 13.5,
    fireDelay: 0.13,
  },
  void: {
    id: "void",
    name: "黑紫暗影机",
    englishName: "Void Phantom",
    subtitle: "裂隙暗影",
    role: "高手向 / 高风险爆发",
    description: "空格短距折跃并留下残影，靠近敌人时暗影输出更高。",
    attack: "折跃、残影、贴脸爆发",
    color: "#b56cff",
    accent: "#6b3dff",
    speed: 388,
    size: 102,
    drawWidth: 90,
    drawHeight: 122,
    sprite: "playerVoidPhantom",
    preview: "./assets/player_void_phantom_sprite.png",
    skillName: "虚空折跃",
    coreCooldown: 12.5,
    fireDelay: 0.115,
  },
};

export const DEFAULT_SHIP_ID = "frost";

export const STAGES = [
  {
    name: "第一关 近地轨道",
    shortName: "近地轨道",
    bossName: "赤潮巡洋舰",
    bossHp: 290,
    bossScore: 3200,
    bossColor: "#ff4fa3",
    maxEnemies: 7,
    warning: "WARNING / 赤潮巡洋舰接近",
  },
  {
    name: "第二关 星尘裂谷",
    shortName: "星尘裂谷",
    bossName: "紫电圣甲",
    bossHp: 410,
    bossScore: 4500,
    bossColor: "#b98cff",
    maxEnemies: 9,
    warning: "WARNING / 紫电圣甲展开",
  },
  {
    name: "第三关 深空王座",
    shortName: "深空王座",
    bossName: "黑曜母舰",
    bossHp: 560,
    bossScore: 6800,
    bossColor: "#ff3d3d",
    maxEnemies: 11,
    warning: "WARNING / 黑曜母舰锁定",
  },
];

export function shipList() {
  return Object.values(SHIPS);
}
